export const LANGUAGES = {
    en: {
        name: "English",
        flag: "https://flagsapi.com/GB/flat/32.png",
        translations: {
            title: "Tic Tac Toe",
            selectMode: 'Select mode:',
            pvpLocal: 'PvP (Local)',
            pvpOnline: 'PvP (Online)',
            vsBot: 'Against Bot',
            boardSize: 'Select the size of the board:',
            botDifficulty: 'Select the difficulty of the bot:',
            difficultyEasy: 'Easy',
            difficultyMedium: 'Medium',
            difficultyImpossible: 'Impossible',
            difficultyAI: 'AI',
            startingPlayer: 'Starting player:',
            startGame: 'Start game',
            restartGame: 'Play again',
            nowPlaying: 'Now playing:',
            enemyThinking: 'Enemy is thinking...',
            gameTie: 'It\'s a tie!',
            gameWin: 'Player {player} wins!',
            helpHeader: 'How to play?'
        }
    },
    pl: {
        name: "Polski",
        flag: "https://flagsapi.com/PL/flat/32.png",
        translations: {
            title: "Kółko i Krzyżyk",
            selectMode: 'Wybierz tryb:',
            pvpLocal: 'PvP (Lokalnie)',
            pvpOnline: 'PvP (Online)',
            vsBot: 'Przeciwko Botowi',
            boardSize: 'Wybierz rozmiar planszy:',
            botDifficulty: 'Wybierz poziom trudności bota:',
            difficultyEasy: 'Łatwy',
            difficultyMedium: 'Średni',
            difficultyImpossible: 'Niemożliwy',
            difficultyAI: 'AI',
            startingPlayer: 'Zaczynający gracz:',
            startGame: 'Rozpocznij grę',
            restartGame: 'Zagraj ponownie',
            nowPlaying: 'Teraz gra:',
            enemyThinking: 'Przeciwnik myśli...',
            gameTie: 'Remis!',
            gameWin: 'Gracz {player} wygrywa!',
            helpHeader: 'Jak grać?'
        }
    },
    es: {
        name: "Español",
        flag: "https://flagsapi.com/ES/flat/32.png",
        translations: {
            title: "Tres en Raya",
            selectMode: 'Seleccionar modo:',
            pvpLocal: 'PvP (Local)',
            pvpOnline: 'PvP (En linea)',
            vsBot: 'Contra Bot',
            boardSize: 'Seleccionar tamaño de la tabla:',
            botDifficulty: 'Seleccionar la dificultad del bot:',
            difficultyEasy: 'Fácil',
            difficultyMedium: 'Medio',
            difficultyImpossible: 'Imposible',
            difficultyAI: 'AI',
            startingPlayer: 'Jugador titular:',
            startGame: 'Iniciar juego',
            restartGame: 'Jugar de nuevo',
            nowPlaying: 'Ahora jugando:',
            enemyThinking: 'El enemigo está pensando...',
            gameTie: '¡Es un empate!',
            gameWin: '¡El jugador {player} gana!',
            helpHeader: '¿Cómo se juega?'
        }
    },
    it: {
        name: "Italiano",
        flag: "https://flagsapi.com/IT/flat/32.png",
        translations: {
            title: "Gioco del tris",
            selectMode: 'Seleziona modalità:',
            pvpLocal: 'PvP (Locale)',
            pvpOnline: 'PvP (Online)',
            vsBot: 'Contro Bot',
            boardSize: 'Seleziona la dimensione della griglia:',
            botDifficulty: 'Seleziona la difficoltà del bot:',
            difficultyEasy: 'Facile',
            difficultyMedium: 'Medio',
            difficultyImpossible: 'Impossibile',
            difficultyAI: 'AI',
            startingPlayer: 'Giocatore iniziale:',
            startGame: 'Inizia partita',
            restartGame: 'Gioca di nuovo',
            nowPlaying: 'Ora sta giocando:',
            enemyThinking: 'Il nemico sta pensando...',
            gameTie: 'È un pareggio!',
            gameWin: 'Giocatore {player} vince!',
            helpHeader: 'Come si gioca?'
        }
    },
    cs: {
        name: "Čeština",
        flag: "https://flagsapi.com/CZ/flat/32.png",
        translations: {
            title: "Piškvorky",
            selectMode: 'Vyberte režim:',
            pvpLocal: 'PvP (Místní)',
            pvpOnline: 'PvP (Online)',
            vsBot: 'Proti botovi',
            boardSize: 'Vyberte velikost hrací desky:',
            botDifficulty: 'Vyberte obtížnost bota:',
            difficultyEasy: 'Snadná',
            difficultyMedium: 'Střední',
            difficultyImpossible: 'Nemožné',
            difficultyAI: 'AI',
            startingPlayer: 'Začínající hráč:',
            startGame: 'Začít hru',
            restartGame: 'Hrát znovu',
            nowPlaying: 'Právě hraje:',
            enemyThinking: 'Nepřítel přemýšlí...',
            gameTie: 'Remíza!',
            gameWin: 'Hráč {player} vyhrál!',
            helpHeader: 'Jak hrát?'
        }
    },
    el: {
        name: "Έλληνικά",
        flag: "https://flagsapi.com/GR/flat/32.png",
        translations: {
            title: "Τρίλιζα",
            selectMode: 'Επιλέξτε λειτουργία:',
            pvpLocal: 'PvP (Τοπικό)',
            pvpOnline: 'PvP (Διαδικτυακό)',
            vsBot: 'Εναντίον Bot',
            boardSize: 'Επιλέξτε το μέγεθος του πίνακα:',
            botDifficulty: 'Επιλέξτε τη δυσκολία του bot:',
            difficultyEasy: 'Εύκολο',
            difficultyMedium: 'Μέτριο',
            difficultyImpossible: 'Αδύνατο',
            difficultyAI: 'AI',
            startingPlayer: 'Αρχικός παίκτης:',
            startGame: 'Έναρξη παιχνιδιού',
            restartGame: 'Παίξε ξανά',
            nowPlaying: 'Τώρα παίζει:',
            enemyThinking: 'Ο εχθρός σκέφτεται...',
            gameTie: 'Είναι ισοπαλία!',
            gameWin: 'Ο Παίκτης {player} κερδίζει!',
            helpHeader: 'Πώς να παίξετε?'
        }
    },
    ar: {
        name: "عربي",
        flag: "https://flagsapi.com/SA/flat/32.png",
        translations: {
            title: "تيك تاك تو",
            selectMode: 'اختار الوضع:',
            pvpLocal: 'PvP (محلي)',
            pvpOnline: 'PvP (أونلاين)',
            vsBot: 'ضد الروبوت',
            boardSize: 'اختار حجم اللوحة:',
            botDifficulty: 'اختار صعوبة الروبوت:',
            difficultyEasy: 'سهل',
            difficultyMedium: 'متوسط',
            difficultyImpossible: 'مستحيل',
            difficultyAI: 'AI',
            startingPlayer: 'اللاعب الأول:',
            startGame: 'ابدأ اللعبة',
            restartGame: 'إعادة اللعب',
            nowPlaying: 'الآن يلعب:',
            enemyThinking: 'العدو يفكر...',
            gameTie: 'إنها تعادل!',
            gameWin: 'اللاعب {player} يفوز!',
            helpHeader: 'كيف تلعب؟'
        }
    },
    zh: {
        name: "繁體中文",
        flag: "https://flagsapi.com/CN/flat/32.png",
        translations: {
            title: "井字遊戲",
            selectMode: '选择模式:',
            pvpLocal: 'PvP (本地)',
            pvpOnline: 'PvP (在线)',
            vsBot: '对战机器人',
            boardSize: '选择棋盘大小:',
            botDifficulty: '选择机器人难度:',
            difficultyEasy: '简单',
            difficultyMedium: '中等',
            difficultyImpossible: '不可能',
            difficultyAI: 'AI',
            startingPlayer: '起始玩家:',
            startGame: '开始游戏',
            restartGame: '重新开始',
            nowPlaying: '现在进行:',
            enemyThinking: '敌人在思考...',
            gameTie: '平局!',
            gameWin: '玩家 {player} 获胜!',
            helpHeader: '如何玩?'
        }
    },
    ja: {
        name: "日本語",
        flag: "https://flagsapi.com/JP/flat/32.png",
        translations: {
            title: "三目並べ",
            selectMode: 'モードを選択:',
            pvpLocal: 'PvP (ローカル)',
            pvpOnline: 'PvP (オンライン)',
            vsBot: 'ボットに対して',
            boardSize: 'ボードのサイズを選択:',
            botDifficulty: 'ボットの難易度を選択:',
            difficultyEasy: '簡単',
            difficultyMedium: '中級',
            difficultyImpossible: '不可能',
            difficultyAI: 'AI',
            startingPlayer: '開始プレイヤー:',
            startGame: 'ゲーム開始',
            restartGame: 'もう一度プレイ',
            nowPlaying: '現在プレイ中:',
            enemyThinking: '敵は考えている...',
            gameTie: '引き分け!',
            gameWin: 'プレイヤー {player} の勝利!',
            helpHeader: 'プレーの仕方は?'
        }
    },
    ko: {
        name: "한국인",
        flag: "https://flagsapi.com/KR/flat/32.png",
        translations: {
            title: "틱택토",
            selectMode: '모드 선택:',
            pvpLocal: 'PvP (로컬)',
            pvpOnline: 'PvP (온라인)',
            vsBot: '봇과의 전투',
            boardSize: '보드 크기 선택:',
            botDifficulty: '봇 난이도 선택:',
            difficultyEasy: '쉬운',
            difficultyMedium: '중간',
            difficultyImpossible: '불가능한',
            difficultyAI: 'AI',
            startingPlayer: '시작 플레이어:',
            startGame: '게임 시작',
            restartGame: '다시 플레이',
            nowPlaying: '현재 플레이 중:',
            enemyThinking: '적이 생각 중...',
            gameTie: '무승부!',
            gameWin: '플레이어 {player} 승리!',
            helpHeader: '어떻게 플레이하나요?'
        }
    }
};