export const LANGUAGES = {
    en: {
        name: "English",
        flag: "https://flagsapi.com/GB/flat/32.png",
        translations: {
            title: "Tic Tac Toe",
            selectMode: 'Select mode:',
            pvpLocal: 'PvP (Local)',
            pvpOnline: 'PvP (Online)',
            vsBot: 'Against Bot',
            boardSize: 'Select the size of the board:',
            botDifficulty: 'Select the difficulty of the bot:',
            difficultyEasy: 'Easy',
            difficultyMedium: 'Medium',
            difficultyImpossible: 'Impossible',
            difficultyAI: 'AI',
            startingPlayer: 'Starting player:',
            startGame: 'Start game',
            restartGame: 'Play again',
            nowPlaying: 'Now playing:',
            enemyThinking: 'Enemy is thinking...',
            gameTie: 'It\'s a tie!',
            gameWin: 'Player {player} wins!',
            gameWon: 'You win!',
            helpHeader: 'How to play?',
            createOnlineGame: 'Create game',
            joinOnlineGame: 'Join game',
            gameName: 'Game name:',
            gameVisibility: 'Game visibility:',
            public: 'Public',
            unlisted: 'Unlisted',
            private: 'Private',
            gamePassword: 'Game password:',
            gameCode: 'Game code:',
            password: 'Password:',
            leaveGame: 'Leave',
            leaveGameConfirm: 'Are you sure you want to leave the game?',
            yes: 'Yes',
            no: 'No',
            player: 'player',
            players: 'players',
            ready: 'Ready',
            notReady: 'Not ready',
            waitingForPlayers: 'Waiting for players...',
            aiMoveError: 'An error occurred while fetching the AI move.',
            createGameError: 'An error occurred while creating the online game.',
            joinGameError: 'An error occurred while joining the online game.',
            listGamesError: 'An error occurred while fetching the list of online games.',
        }
    },
    pl: {
        name: "Polski",
        flag: "https://flagsapi.com/PL/flat/32.png",
        translations: {
            title: "Kółko i Krzyżyk",
            selectMode: 'Wybierz tryb:',
            pvpLocal: 'PvP (Lokalnie)',
            pvpOnline: 'PvP (Online)',
            vsBot: 'Przeciwko Botowi',
            boardSize: 'Wybierz rozmiar planszy:',
            botDifficulty: 'Wybierz poziom trudności bota:',
            difficultyEasy: 'Łatwy',
            difficultyMedium: 'Średni',
            difficultyImpossible: 'Niemożliwy',
            difficultyAI: 'AI',
            startingPlayer: 'Zaczynający gracz:',
            startGame: 'Rozpocznij grę',
            restartGame: 'Zagraj ponownie',
            nowPlaying: 'Teraz gra:',
            enemyThinking: 'Przeciwnik myśli...',
            gameTie: 'Remis!',
            gameWin: 'Gracz {player} wygrywa!',
            gameWon: 'Wygrałeś!',
            helpHeader: 'Jak grać?',
            createOnlineGame: 'Utwórz grę',
            joinOnlineGame: 'Dołącz do gry',
            gameName: 'Nazwa gry:',
            gameVisibility: 'Widoczność gry:',
            public: 'Publiczna',
            unlisted: 'Niepubliczna',
            private: 'Prywatna',
            gamePassword: 'Hasło do gry:',
            gameCode: 'Kod gry:',
            password: 'Hasło:',
            leaveGame: 'Opuść',
            leaveGameConfirm: 'Czy na pewno chcesz opuścić grę?',
            yes: 'Tak',
            no: 'Nie',
            ready: 'Gotowy',
            notReady: 'Niegotowy',
            waitingForPlayers: 'Oczekiwanie na graczy...',
        }
    },
    es: {
        name: "Español",
        flag: "https://flagsapi.com/ES/flat/32.png",
        translations: {
            title: "Tres en Raya",
            selectMode: 'Seleccionar modo:',
            pvpLocal: 'PvP (Local)',
            pvpOnline: 'PvP (En linea)',
            vsBot: 'Contra Bot',
            boardSize: 'Seleccionar tamaño de la tabla:',
            botDifficulty: 'Seleccionar la dificultad del bot:',
            difficultyEasy: 'Fácil',
            difficultyMedium: 'Medio',
            difficultyImpossible: 'Imposible',
            difficultyAI: 'AI',
            startingPlayer: 'Jugador titular:',
            startGame: 'Iniciar juego',
            restartGame: 'Jugar de nuevo',
            nowPlaying: 'Ahora jugando:',
            enemyThinking: 'El enemigo está pensando...',
            gameTie: '¡Es un empate!',
            gameWin: '¡El jugador {player} gana!',
            gameWon: '¡Ganaste!',
            helpHeader: '¿Cómo se juega?',
            createOnlineGame: 'Crear juego',
            joinOnlineGame: 'Unirse al juego',
            gameName: 'Nombre del juego:',
            gameVisibility: 'Visibilidad del juego:',
            public: 'Público',
            unlisted: 'No listado',
            private: 'Privado',
            gamePassword: 'Contraseña del juego:',
            gameCode: 'Código del juego:',
            password: 'Contraseña:',
            leaveGame: 'Dejar',
            leaveGameConfirm: '¿Estás seguro de que quieres abandonar el juego?',
            yes: 'Sí',
            no: 'No',
            ready: 'Listo',
            notReady: 'No listo',
            waitingForPlayers: 'Esperando jugadores...'
        }
    },
    it: {
        name: "Italiano",
        flag: "https://flagsapi.com/IT/flat/32.png",
        translations: {
            title: "Gioco del tris",
            selectMode: 'Seleziona modalità:',
            pvpLocal: 'PvP (Locale)',
            pvpOnline: 'PvP (Online)',
            vsBot: 'Contro Bot',
            boardSize: 'Seleziona la dimensione della griglia:',
            botDifficulty: 'Seleziona la difficoltà del bot:',
            difficultyEasy: 'Facile',
            difficultyMedium: 'Medio',
            difficultyImpossible: 'Impossibile',
            difficultyAI: 'AI',
            startingPlayer: 'Giocatore iniziale:',
            startGame: 'Inizia partita',
            restartGame: 'Gioca di nuovo',
            nowPlaying: 'Ora sta giocando:',
            enemyThinking: 'Il nemico sta pensando...',
            gameTie: 'È un pareggio!',
            gameWin: 'Giocatore {player} vince!',
            gameWon: 'Hai vinto!',
            helpHeader: 'Come si gioca?',
            createOnlineGame: 'Crea gioco',
            joinOnlineGame: 'Unisciti al gioco',
            gameName: 'Nome del gioco:',
            gameVisibility: 'Visibilità del gioco:',
            public: 'Pubblico',
            unlisted: 'Non elencato',
            private: 'Privato',
            gamePassword: 'Password del gioco:',
            gameCode: 'Codice del gioco:',
            password: 'Password:',
            leaveGame: 'Lascia',
            leaveGameConfirm: 'Sei sicuro di voler lasciare il gioco?',
            yes: 'Sì',
            no: 'No',
            ready: 'Pronto',
            notReady: 'Non pronto',
            waitingForPlayers: 'In attesa di giocatori...'
        }
    },
    cs: {
        name: "Čeština",
        flag: "https://flagsapi.com/CZ/flat/32.png",
        translations: {
            title: "Piškvorky",
            selectMode: 'Vyberte režim:',
            pvpLocal: 'PvP (Místní)',
            pvpOnline: 'PvP (Online)',
            vsBot: 'Proti botovi',
            boardSize: 'Vyberte velikost hrací desky:',
            botDifficulty: 'Vyberte obtížnost bota:',
            difficultyEasy: 'Snadná',
            difficultyMedium: 'Střední',
            difficultyImpossible: 'Nemožné',
            difficultyAI: 'AI',
            startingPlayer: 'Začínající hráč:',
            startGame: 'Začít hru',
            restartGame: 'Hrát znovu',
            nowPlaying: 'Právě hraje:',
            enemyThinking: 'Nepřítel přemýšlí...',
            gameTie: 'Remíza!',
            gameWin: 'Hráč {player} vyhrál!',
            gameWon: 'Vyhrál jsi!',
            helpHeader: 'Jak hrát?',
            createOnlineGame: 'Vytvořit hru',
            joinOnlineGame: 'Připojit se ke hře',
            gameName: 'Název hry:',
            gameVisibility: 'Viditelnost hry:',
            public: 'Veřejné',
            unlisted: 'Neveřejné',
            private: 'Soukromé',
            gamePassword: 'Heslo hry:',
            gameCode: 'Kód hry:',
            password: 'Heslo:',
            leaveGame: 'Odejít',
            leaveGameConfirm: 'Opravdu chcete odejít z hry?',
            yes: 'Ano',
            no: 'Ne',
            ready: 'Připraven',
            notReady: 'Nepřipraven',
            waitingForPlayers: 'Čekání na hráče...'
        }
    },
    el: {
        name: "Έλληνικά",
        flag: "https://flagsapi.com/GR/flat/32.png",
        translations: {
            title: "Τρίλιζα",
            selectMode: 'Επιλέξτε λειτουργία:',
            pvpLocal: 'PvP (Τοπικό)',
            pvpOnline: 'PvP (Διαδικτυακό)',
            vsBot: 'Εναντίον Bot',
            boardSize: 'Επιλέξτε το μέγεθος του πίνακα:',
            botDifficulty: 'Επιλέξτε τη δυσκολία του bot:',
            difficultyEasy: 'Εύκολο',
            difficultyMedium: 'Μέτριο',
            difficultyImpossible: 'Αδύνατο',
            difficultyAI: 'AI',
            startingPlayer: 'Αρχικός παίκτης:',
            startGame: 'Έναρξη παιχνιδιού',
            restartGame: 'Παίξε ξανά',
            nowPlaying: 'Τώρα παίζει:',
            enemyThinking: 'Ο εχθρός σκέφτεται...',
            gameTie: 'Είναι ισοπαλία!',
            gameWin: 'Ο Παίκτης {player} κερδίζει!',
            gameWon: 'Κέρδισες!',
            helpHeader: 'Πώς να παίξετε?',
            createOnlineGame: 'Δημιουργία παιχνιδιού',
            joinOnlineGame: 'Συμμετοχή στο παιχνίδι',
            gameName: 'Όνομα παιχνιδιού:',
            gameVisibility: 'Ορατότητα παιχνιδιού:',
            public: 'Δημόσιο',
            unlisted: 'Μη δημόσιο',
            private: 'Ιδιωτικό',
            gamePassword: 'Κωδικός παιχνιδιού:',
            gameCode: 'Κωδικός παιχνιδιού:',
            password: 'Κωδικός:',
            leaveGame: 'Αφήστε',
            leaveGameConfirm: 'Είστε σίγουροι ότι θέλετε να αφήσετε το παιχνίδι?',
            yes: 'Ναί',
            no: 'Όχι',
            ready: 'Έτοιμος',
            notReady: 'Μη έτοιμος',
            waitingForPlayers: 'Αναμονή για παίκτες...'
        }
    },
    ar: {
        name: "عربي",
        flag: "https://flagsapi.com/SA/flat/32.png",
        translations: {
            title: "تيك تاك تو",
            selectMode: 'اختار الوضع:',
            pvpLocal: 'PvP (محلي)',
            pvpOnline: 'PvP (أونلاين)',
            vsBot: 'ضد الروبوت',
            boardSize: 'اختار حجم اللوحة:',
            botDifficulty: 'اختار صعوبة الروبوت:',
            difficultyEasy: 'سهل',
            difficultyMedium: 'متوسط',
            difficultyImpossible: 'مستحيل',
            difficultyAI: 'AI',
            startingPlayer: 'اللاعب الأول:',
            startGame: 'ابدأ اللعبة',
            restartGame: 'إعادة اللعب',
            nowPlaying: 'الآن يلعب:',
            enemyThinking: 'العدو يفكر...',
            gameTie: 'إنها تعادل!',
            gameWin: 'اللاعب {player} يفوز!',
            gameWon: 'لقد فزت!',
            helpHeader: 'كيف تلعب؟',
            createOnlineGame: 'إنشاء لعبة',
            joinOnlineGame: 'انضم إلى اللعبة',
            gameName: 'اسم اللعبة:',
            gameVisibility: 'رؤية اللعبة:',
            public: 'عام',
            unlisted: 'غير مدرج',
            private: 'خاص',
            gamePassword: 'كلمة مرور اللعبة:',
            gameCode: 'رمز اللعبة:',
            password: 'كلمة السر:',
            leaveGame: 'غادر',
            leaveGameConfirm: 'هل أنت متأكد أنك تريد مغادرة اللعبة؟',
            yes: 'نعم',
            no: 'لا',
            ready: 'جاهز',
            notReady: 'غير جاهز',
            waitingForPlayers: 'في انتظار اللاعبين...'
        }
    },
    zh: {
        name: "繁體中文",
        flag: "https://flagsapi.com/CN/flat/32.png",
        translations: {
            title: "井字遊戲",
            selectMode: '选择模式:',
            pvpLocal: 'PvP (本地)',
            pvpOnline: 'PvP (在线)',
            vsBot: '对战机器人',
            boardSize: '选择棋盘大小:',
            botDifficulty: '选择机器人难度:',
            difficultyEasy: '简单',
            difficultyMedium: '中等',
            difficultyImpossible: '不可能',
            difficultyAI: 'AI',
            startingPlayer: '起始玩家:',
            startGame: '开始游戏',
            restartGame: '重新开始',
            nowPlaying: '现在进行:',
            enemyThinking: '敌人在思考...',
            gameTie: '平局!',
            gameWin: '玩家 {player} 获胜!',
            gameWon: '你赢了!',
            helpHeader: '如何玩?',
            createOnlineGame: '创建游戏',
            joinOnlineGame: '加入游戏',
            gameName: '游戏名称:',
            gameVisibility: '游戏可见性:',
            public: '公开',
            unlisted: '未列出',
            private: '私人',
            gamePassword: '游戏密码:',
            gameCode: '游戏代码:',
            password: '密码:',
            leaveGame: '离开',
            leaveGameConfirm: '您确定要离开游戏吗?',
            yes: '是',
            no: '否',
            ready: '准备',
            notReady: '未准备好',
            waitingForPlayers: '等待玩家...'
        }
    },
    ja: {
        name: "日本語",
        flag: "https://flagsapi.com/JP/flat/32.png",
        translations: {
            title: "三目並べ",
            selectMode: 'モードを選択:',
            pvpLocal: 'PvP (ローカル)',
            pvpOnline: 'PvP (オンライン)',
            vsBot: 'ボットに対して',
            boardSize: 'ボードのサイズを選択:',
            botDifficulty: 'ボットの難易度を選択:',
            difficultyEasy: '簡単',
            difficultyMedium: '中級',
            difficultyImpossible: '不可能',
            difficultyAI: 'AI',
            startingPlayer: '開始プレイヤー:',
            startGame: 'ゲーム開始',
            restartGame: 'もう一度プレイ',
            nowPlaying: '現在プレイ中:',
            enemyThinking: '敵は考えている...',
            gameTie: '引き分け!',
            gameWin: 'プレイヤー {player} の勝利!',
            gameWon: 'あなたの勝ち!',
            helpHeader: 'プレーの仕方は?',
            createOnlineGame: 'ゲームを作成',
            joinOnlineGame: 'ゲームに参加',
            gameName: 'ゲーム名:',
            gameVisibility: 'ゲームの可視性:',
            public: '公開',
            unlisted: '非公開',
            private: 'プライベート',
            gamePassword: 'ゲームのパスワード:',
            gameCode: 'ゲームコード:',
            password: 'パスワード:',
            leaveGame: '去る',
            leaveGameConfirm: 'ゲームを終了してもよろしいですか?',
            yes: 'はい',
            no: 'いいえ',
            ready: '準備完了',
            notReady: '準備ができていない',
            waitingForPlayers: 'プレイヤーを待っています...'
        }
    },
    ko: {
        name: "한국인",
        flag: "https://flagsapi.com/KR/flat/32.png",
        translations: {
            title: "틱택토",
            selectMode: '모드 선택:',
            pvpLocal: 'PvP (로컬)',
            pvpOnline: 'PvP (온라인)',
            vsBot: '봇과의 전투',
            boardSize: '보드 크기 선택:',
            botDifficulty: '봇 난이도 선택:',
            difficultyEasy: '쉬운',
            difficultyMedium: '중간',
            difficultyImpossible: '불가능한',
            difficultyAI: 'AI',
            startingPlayer: '시작 플레이어:',
            startGame: '게임 시작',
            restartGame: '다시 플레이',
            nowPlaying: '현재 플레이 중:',
            enemyThinking: '적이 생각 중...',
            gameTie: '무승부!',
            gameWin: '플레이어 {player} 승리!',
            gameWon: '당신이 이겼습니다!',
            helpHeader: '어떻게 플레이하나요?',
            createOnlineGame: '게임 만들기',
            joinOnlineGame: '게임 참가',
            gameName: '게임 이름:',
            gameVisibility: '게임 가시성:',
            public: '공개',
            unlisted: '비공개',
            private: '비공개',
            gamePassword: '게임 비밀번호:',
            gameCode: '게임 코드:',
            password: '암호:',
            leaveGame: '떠나다',
            leaveGameConfirm: '게임을 나가시겠습니까?',
            yes: '예',
            no: '아니',
            ready: '준비 완료',
            notReady: '준비되지 않음',
            waitingForPlayers: '플레이어 대기 중...'
        }
    }
};