export const LANGUAGES = {
    en: {
        name: "English",
        flag: "https://flagsapi.com/GB/flat/32.png",
        translations: {
            title: "Tic Tac Toe",
            selectMode: 'Select mode:',
            pvpLocal: 'PvP (Local)',
            pvpOnline: 'PvP (Online)',
            vsBot: 'Against Bot',
            boardSize: 'Select the size of the board:',
            botDifficulty: 'Select the difficulty of the bot:',
            difficultyEasy: 'Easy',
            difficultyMedium: 'Medium',
            difficultyImpossible: 'Impossible',
            difficultyAI: 'AI',
            startingPlayer: 'Starting player:',
            startGame: 'Start game',
            restartGame: 'Play again',
            nowPlaying: 'Now playing:',
            enemyThinking: 'Enemy is thinking...',
            gameTie: 'It\'s a tie!',
            gameWin: 'Player {player} wins!',
            gameWon: 'You win!',
            helpHeader: 'How to play?',
            online: 'Online',
            about: 'About me',
            createOnlineGame: 'Create game',
            joinOnlineGame: 'Join game',
            gameName: 'Game name:',
            gameVisibility: 'Game visibility:',
            public: 'Public',
            unlisted: 'Unlisted',
            private: 'Private',
            gamePassword: 'Game password:',
            gameCode: 'Game code:',
            password: 'Password:',
            leaveGame: 'Leave',
            leaveGameConfirm: 'Are you sure you want to leave the game?',
            yes: 'Yes',
            no: 'No',
            player: 'player',
            players: 'players',
            ready: 'Ready',
            notReady: 'Not ready',
            waitingForPlayers: 'Waiting for players...',
            copyLink: 'Join link copied to clipboard',
            copyCode: 'Game code copied to clipboard',
            invalidSize: 'Invalid board size. Please select a size between 3 and 10.',
            invalidGameName: 'Invalid game name format. Please use only letters, numbers and spaces. Length must be between 3 and 20 characters.',
            invalidPasswordFormat: 'Invalid password format. Please use only letters, numbers and special characters. Length must be between 6 and 20 characters.',
            invalidGameCode: 'Invalid game code format. Please use only letters and numbers. Length must be 6 characters.',
            badRequest: 'An error occurred while joining the game. (Bad Request)',
            unauthorized: 'Failed to authenticate, please try again.',
            forbidden: 'You are not allowed to join this game.',
            notFound: 'Could not find the game.',
            internalServerError: 'An error occurred while joining the game.',
            notAllowed: 'You are not allowed to perform this action.',
            gameNotFound: 'Game not found. Please check the code and try again.',
            aiMoveError: 'An error occurred while fetching the AI move.',
            createGameError: 'An error occurred while creating the online game.',
            joinGameError: 'An error occurred while joining the online game.',
            listGamesError: 'An error occurred while fetching the list of online games.',
        }
    },
    pl: {
        name: "Polski",
        flag: "https://flagsapi.com/PL/flat/32.png",
        translations: {
            title: "Kółko i Krzyżyk",
            selectMode: 'Wybierz tryb:',
            pvpLocal: 'PvP (Lokalnie)',
            pvpOnline: 'PvP (Online)',
            vsBot: 'Przeciwko Botowi',
            boardSize: 'Wybierz rozmiar planszy:',
            botDifficulty: 'Wybierz poziom trudności bota:',
            difficultyEasy: 'Łatwy',
            difficultyMedium: 'Średni',
            difficultyImpossible: 'Niemożliwy',
            difficultyAI: 'AI',
            startingPlayer: 'Zaczynający gracz:',
            startGame: 'Rozpocznij grę',
            restartGame: 'Zagraj ponownie',
            nowPlaying: 'Teraz gra:',
            enemyThinking: 'Przeciwnik myśli...',
            gameTie: 'Remis!',
            gameWin: 'Gracz {player} wygrywa!',
            gameWon: 'Wygrałeś!',
            helpHeader: 'Jak grać?',
            online: 'Online',
            about: 'O mnie',
            createOnlineGame: 'Utwórz grę',
            joinOnlineGame: 'Dołącz do gry',
            gameName: 'Nazwa gry:',
            gameVisibility: 'Widoczność gry:',
            public: 'Publiczna',
            unlisted: 'Niepubliczna',
            private: 'Prywatna',
            gamePassword: 'Hasło do gry:',
            gameCode: 'Kod gry:',
            password: 'Hasło:',
            leaveGame: 'Opuść',
            leaveGameConfirm: 'Czy na pewno chcesz opuścić grę?',
            yes: 'Tak',
            no: 'Nie',
            ready: 'Gotowy',
            notReady: 'Niegotowy',
            waitingForPlayers: 'Oczekiwanie na graczy...',
            copyLink: 'Link dołączenia skopiowany do schowka',
            copyCode: 'Kod gry skopiowany do schowka',
            invalidSize: 'Nieprawidłowy rozmiar planszy. Wybierz rozmiar między 3 a 10.',
            invalidGameName: 'Nieprawidłowy format nazwy gry. Użyj tylko liter, cyfr i spacji. Długość musi wynosić od 3 do 20 znaków.',
            invalidPasswordFormat: 'Nieprawidłowy format hasła. Użyj tylko liter, cyfr i znaków specjalnych. Długość musi wynosić od 6 do 20 znaków.',
            invalidGameCode: 'Nieprawidłowy format kodu gry. Użyj tylko liter i cyfr. Długość musi wynosić 6 znaków.',
            badRequest: 'Wystąpił błąd podczas dołączania do gry. (Nieprawidłowe żądanie)',
            unauthorized: 'Uwierzytelnienie nie powiodło się, spróbuj ponownie.',
            forbidden: 'Nie masz uprawnień do dołączenia do tej gry.',
            notFound: 'Nie znaleziono gry.',
            internalServerError: 'Wystąpił błąd podczas dołączania do gry.',
            notAllowed: 'Nie masz uprawnień do wykonania tej akcji.',
            gameNotFound: 'Gra nie znaleziona. Sprawdź kod i spróbuj ponownie.',
            aiMoveError: 'Wystąpił błąd podczas pobierania ruchu AI.',
            createGameError: 'Wystąpił błąd podczas tworzenia gry online.',
            joinGameError: 'Wystąpił błąd podczas dołączania do gry online.',
            listGamesError: 'Wystąpił błąd podczas pobierania listy gier online.',
        }
    },
    es: {
        name: "Español",
        flag: "https://flagsapi.com/ES/flat/32.png",
        translations: {
            title: "Tres en Raya",
            selectMode: 'Seleccionar modo:',
            pvpLocal: 'PvP (Local)',
            pvpOnline: 'PvP (En linea)',
            vsBot: 'Contra Bot',
            boardSize: 'Seleccionar tamaño de la tabla:',
            botDifficulty: 'Seleccionar la dificultad del bot:',
            difficultyEasy: 'Fácil',
            difficultyMedium: 'Medio',
            difficultyImpossible: 'Imposible',
            difficultyAI: 'AI',
            startingPlayer: 'Jugador titular:',
            startGame: 'Iniciar juego',
            restartGame: 'Jugar de nuevo',
            nowPlaying: 'Ahora jugando:',
            enemyThinking: 'El enemigo está pensando...',
            gameTie: '¡Es un empate!',
            gameWin: '¡El jugador {player} gana!',
            gameWon: '¡Ganaste!',
            helpHeader: '¿Cómo se juega?',
            online: 'En línea',
            about: 'Sobre mí',
            createOnlineGame: 'Crear juego',
            joinOnlineGame: 'Unirse al juego',
            gameName: 'Nombre del juego:',
            gameVisibility: 'Visibilidad del juego:',
            public: 'Público',
            unlisted: 'No listado',
            private: 'Privado',
            gamePassword: 'Contraseña del juego:',
            gameCode: 'Código del juego:',
            password: 'Contraseña:',
            leaveGame: 'Dejar',
            leaveGameConfirm: '¿Estás seguro de que quieres abandonar el juego?',
            yes: 'Sí',
            no: 'No',
            ready: 'Listo',
            notReady: 'No listo',
            waitingForPlayers: 'Esperando jugadores...',
            copyLink: 'Enlace de unión copiado al portapapeles',
            copyCode: 'Código de juego copiado al portapapeles',
            invalidSize: 'Tamaño de tablero no válido. Seleccione un tamaño entre 3 y 10.',
            invalidGameName: 'Formato de nombre de juego no válido. Utilice solo letras, números y espacios. La longitud debe estar entre 3 y 20 caracteres.',
            invalidPasswordFormat: 'Formato de contraseña no válido. Utilice solo letras, números y caracteres especiales. La longitud debe estar entre 6 y 20 caracteres.',
            invalidGameCode: 'Formato de código de juego no válido. Utilice solo letras y números. La longitud debe ser de 6 caracteres.',
            badRequest: 'Se produjo un error al unirse al juego. (Solicitud incorrecta)',
            unauthorized: 'Error de autenticación, por favor inténtelo de nuevo.',
            forbidden: 'No tienes permiso para unirte a este juego.',
            notFound: 'No se pudo encontrar el juego.',
            internalServerError: 'Se produjo un error al unirse al juego.',
            notAllowed: 'No tienes permiso para realizar esta acción.',
            gameNotFound: 'Juego no encontrado. Por favor, comprueba el código e inténtalo de nuevo.',
            aiMoveError: 'Se produjo un error al obtener el movimiento de la IA.',
            createGameError: 'Se produjo un error al crear el juego en línea.',
            joinGameError: 'Se produjo un error al unirse al juego en línea.',
            listGamesError: 'Se produjo un error al obtener la lista de juegos en línea.',
        }
    },
    it: {
        name: "Italiano",
        flag: "https://flagsapi.com/IT/flat/32.png",
        translations: {
            title: "Gioco del tris",
            selectMode: 'Seleziona modalità:',
            pvpLocal: 'PvP (Locale)',
            pvpOnline: 'PvP (Online)',
            vsBot: 'Contro Bot',
            boardSize: 'Seleziona la dimensione della griglia:',
            botDifficulty: 'Seleziona la difficoltà del bot:',
            difficultyEasy: 'Facile',
            difficultyMedium: 'Medio',
            difficultyImpossible: 'Impossibile',
            difficultyAI: 'AI',
            startingPlayer: 'Giocatore iniziale:',
            startGame: 'Inizia partita',
            restartGame: 'Gioca di nuovo',
            nowPlaying: 'Ora sta giocando:',
            enemyThinking: 'Il nemico sta pensando...',
            gameTie: 'È un pareggio!',
            gameWin: 'Giocatore {player} vince!',
            gameWon: 'Hai vinto!',
            helpHeader: 'Come si gioca?',
            online: 'Online',
            about: 'Su di me',
            createOnlineGame: 'Crea gioco',
            joinOnlineGame: 'Unisciti al gioco',
            gameName: 'Nome del gioco:',
            gameVisibility: 'Visibilità del gioco:',
            public: 'Pubblico',
            unlisted: 'Non elencato',
            private: 'Privato',
            gamePassword: 'Password del gioco:',
            gameCode: 'Codice del gioco:',
            password: 'Password:',
            leaveGame: 'Lascia',
            leaveGameConfirm: 'Sei sicuro di voler lasciare il gioco?',
            yes: 'Sì',
            no: 'No',
            ready: 'Pronto',
            notReady: 'Non pronto',
            waitingForPlayers: 'In attesa di giocatori...',
            copyLink: 'Link di unione copiato negli appunti',
            copyCode: 'Codice del gioco copiato negli appunti',
            invalidSize: 'Dimensione della griglia non valida. Seleziona una dimensione tra 3 e 10.',
            invalidGameName: 'Formato del nome del gioco non valido. Utilizzare solo lettere, numeri e spazi. La lunghezza deve essere compresa tra 3 e 20 caratteri.',
            invalidPasswordFormat: 'Formato password non valido. Utilizzare solo lettere, numeri e caratteri speciali. La lunghezza deve essere compresa tra 6 e 20 caratteri.',
            invalidGameCode: 'Formato del codice del gioco non valido. Utilizzare solo lettere e numeri. La lunghezza deve essere di 6 caratteri.',
            badRequest: 'Si è verificato un errore durante l\'unione al gioco. (Richiesta errata)',
            unauthorized: 'Autenticazione fallita, riprova.',
            forbidden: 'Non sei autorizzato a unirti a questo gioco.',
            notFound: 'Impossibile trovare il gioco.',
            internalServerError: 'Si è verificato un errore durante l\'unione al gioco.',
            notAllowed: 'Non sei autorizzato a eseguire questa azione.',
            gameNotFound: 'Gioco non trovato. Controlla il codice e riprova.',
            aiMoveError: 'Si è verificato un errore durante il recupero della mossa AI.',
            createGameError: 'Si è verificato un errore durante la creazione del gioco online.',
            joinGameError: 'Si è verificato un errore durante l\'unione al gioco online.',
            listGamesError: 'Si è verificato un errore durante il recupero dell\'elenco dei giochi online.',
        }
    },
    cs: {
        name: "Čeština",
        flag: "https://flagsapi.com/CZ/flat/32.png",
        translations: {
            title: "Piškvorky",
            selectMode: 'Vyberte režim:',
            pvpLocal: 'PvP (Místní)',
            pvpOnline: 'PvP (Online)',
            vsBot: 'Proti botovi',
            boardSize: 'Vyberte velikost hrací desky:',
            botDifficulty: 'Vyberte obtížnost bota:',
            difficultyEasy: 'Snadná',
            difficultyMedium: 'Střední',
            difficultyImpossible: 'Nemožné',
            difficultyAI: 'AI',
            startingPlayer: 'Začínající hráč:',
            startGame: 'Začít hru',
            restartGame: 'Hrát znovu',
            nowPlaying: 'Právě hraje:',
            enemyThinking: 'Nepřítel přemýšlí...',
            gameTie: 'Remíza!',
            gameWin: 'Hráč {player} vyhrál!',
            gameWon: 'Vyhrál jsi!',
            helpHeader: 'Jak hrát?',
            online: 'Online',
            about: 'O mně',
            createOnlineGame: 'Vytvořit hru',
            joinOnlineGame: 'Připojit se ke hře',
            gameName: 'Název hry:',
            gameVisibility: 'Viditelnost hry:',
            public: 'Veřejné',
            unlisted: 'Neveřejné',
            private: 'Soukromé',
            gamePassword: 'Heslo hry:',
            gameCode: 'Kód hry:',
            password: 'Heslo:',
            leaveGame: 'Odejít',
            leaveGameConfirm: 'Opravdu chcete odejít z hry?',
            yes: 'Ano',
            no: 'Ne',
            ready: 'Připraven',
            notReady: 'Nepřipraven',
            waitingForPlayers: 'Čekání na hráče...',
            copyLink: 'Odkaz na připojení zkopírován do schránky',
            copyCode: 'Kód hry zkopírován do schránky',
            invalidSize: 'Neplatná velikost hrací desky. Vyberte velikost mezi 3 a 10.',
            invalidGameName: 'Neplatný formát názvu hry. Použijte pouze písmena, čísla a mezery. Délka musí být mezi 3 a 20 znaky.',
            invalidPasswordFormat: 'Neplatný formát hesla. Použijte pouze písmena, čísla a speciální znaky. Délka musí být mezi 6 a 20 znaky.',
            invalidGameCode: 'Neplatný formát kódu hry. Použijte pouze písmena a čísla. Délka musí být 6 znaků.',
            badRequest: 'Při připojování k hře došlo k chybě. (Špatný požadavek)',
            unauthorized: 'Autentizace se nezdařila, zkuste to znovu.',
            forbidden: 'Nemáte povolení připojit se k této hře.',
            notFound: 'Hru se nepodařilo najít.',
            internalServerError: 'Při připojování k hře došlo k chybě.',
            notAllowed: 'Nemáte povolení provést tuto akci.',
            gameNotFound: 'Hra nebyla nalezena. Zkontrolujte kód a zkuste to znovu.',
            aiMoveError: 'Při získávání tahu AI došlo k chybě.',
            createGameError: 'Při vytváření online hry došlo k chybě.',
            joinGameError: 'Při připojování k online hře došlo k chybě.',
            listGamesError: 'Při získávání seznamu online her došlo k chybě.',
        }
    },
    el: {
        name: "Έλληνικά",
        flag: "https://flagsapi.com/GR/flat/32.png",
        translations: {
            title: "Τρίλιζα",
            selectMode: 'Επιλέξτε λειτουργία:',
            pvpLocal: 'PvP (Τοπικό)',
            pvpOnline: 'PvP (Διαδικτυακό)',
            vsBot: 'Εναντίον Bot',
            boardSize: 'Επιλέξτε το μέγεθος του πίνακα:',
            botDifficulty: 'Επιλέξτε τη δυσκολία του bot:',
            difficultyEasy: 'Εύκολο',
            difficultyMedium: 'Μέτριο',
            difficultyImpossible: 'Αδύνατο',
            difficultyAI: 'AI',
            startingPlayer: 'Αρχικός παίκτης:',
            startGame: 'Έναρξη παιχνιδιού',
            restartGame: 'Παίξε ξανά',
            nowPlaying: 'Τώρα παίζει:',
            enemyThinking: 'Ο εχθρός σκέφτεται...',
            gameTie: 'Είναι ισοπαλία!',
            gameWin: 'Ο Παίκτης {player} κερδίζει!',
            gameWon: 'Κέρδισες!',
            helpHeader: 'Πώς να παίξετε?',
            online: 'Διαδικτυακό',
            about: 'Σχετικά με εμένα',
            createOnlineGame: 'Δημιουργία παιχνιδιού',
            joinOnlineGame: 'Συμμετοχή στο παιχνίδι',
            gameName: 'Όνομα παιχνιδιού:',
            gameVisibility: 'Ορατότητα παιχνιδιού:',
            public: 'Δημόσιο',
            unlisted: 'Μη δημόσιο',
            private: 'Ιδιωτικό',
            gamePassword: 'Κωδικός παιχνιδιού:',
            gameCode: 'Κωδικός παιχνιδιού:',
            password: 'Κωδικός:',
            leaveGame: 'Αφήστε',
            leaveGameConfirm: 'Είστε σίγουροι ότι θέλετε να αφήσετε το παιχνίδι?',
            yes: 'Ναί',
            no: 'Όχι',
            ready: 'Έτοιμος',
            notReady: 'Μη έτοιμος',
            waitingForPlayers: 'Αναμονή για παίκτες...',
            copyLink: 'Ο σύνδεσμος συμμετοχής αντιγράφηκε στο πρόχειρο',
            copyCode: 'Ο κωδικός παιχνιδιού αντιγράφηκε στο πρόχειρο',
            invalidSize: 'Μη έγκυρο μέγεθος πίνακα. Επιλέξτε μέγεθος μεταξύ 3 και 10.',
            invalidGameName: 'Μη έγκυρη μορφή ονόματος παιχνιδιού. Χρησιμοποιήστε μόνο γράμματα, αριθμούς και κενά. Το μήκος πρέπει να είναι μεταξύ 3 και 20 χαρακτήρων.',
            invalidPasswordFormat: 'Μη έγκυρη μορφή κωδικού πρόσβασης. Χρησιμοποιήστε μόνο γράμματα, αριθμούς και ειδικούς χαρακτήρες. Το μήκος πρέπει να είναι μεταξύ 6 και 20 χαρακτήρων.',
            invalidGameCode: 'Μη έγκυρη μορφή κωδικού παιχνιδιού. Χρησιμοποιήστε μόνο γράμματα και αριθμούς. Το μήκος πρέπει να είναι 6 χαρακτήρες.',
            badRequest: 'Παρουσιάστηκε σφάλμα κατά τη συμμετοχή στο παιχνίδι. (Λανθασμένο αίτημα)',
            unauthorized: 'Αποτυχία πιστοποίησης, παρακαλώ δοκιμάστε ξανά.',
            forbidden: 'Δεν σας επιτρέπεται να συμμετάσχετε σε αυτό το παιχνίδι.',
            notFound: 'Δεν ήταν δυνατή η εύρεση του παιχνιδιού.',
            internalServerError: 'Παρουσιάστηκε σφάλμα κατά τη συμμετοχή στο παιχνίδι.',
            notAllowed: 'Δεν σας επιτρέπεται να εκτελέσετε αυτήν την ενέργεια.',
            gameNotFound: 'Παιχνίδι δεν βρέθηκε. Ελέγξτε τον κωδικό και δοκιμάστε ξανά.',
            aiMoveError: 'Παρουσιάστηκε σφάλμα κατά τη λήψη της κίνησης AI.',
            createGameError: 'Παρουσιάστηκε σφάλμα κατά τη δημιουργία του διαδικτυακού παιχνιδιού.',
            joinGameError: 'Παρουσιάστηκε σφάλμα κατά τη συμμετοχή στο διαδικτυακό παιχνίδι.',
            listGamesError: 'Παρουσιάστηκε σφάλμα κατά τη λήψη της λίστας των διαδικτυακών παιχνιδιών.',
        }
    },
    ar: {
        name: "عربي",
        flag: "https://flagsapi.com/SA/flat/32.png",
        translations: {
            title: "تيك تاك تو",
            selectMode: 'اختار الوضع:',
            pvpLocal: 'PvP (محلي)',
            pvpOnline: 'PvP (أونلاين)',
            vsBot: 'ضد الروبوت',
            boardSize: 'اختار حجم اللوحة:',
            botDifficulty: 'اختار صعوبة الروبوت:',
            difficultyEasy: 'سهل',
            difficultyMedium: 'متوسط',
            difficultyImpossible: 'مستحيل',
            difficultyAI: 'AI',
            startingPlayer: 'اللاعب الأول:',
            startGame: 'ابدأ اللعبة',
            restartGame: 'إعادة اللعب',
            nowPlaying: 'الآن يلعب:',
            enemyThinking: 'العدو يفكر...',
            gameTie: 'إنها تعادل!',
            gameWin: 'اللاعب {player} يفوز!',
            gameWon: 'لقد فزت!',
            helpHeader: 'كيف تلعب؟',
            online: 'أونلاين',
            about: 'عني',
            createOnlineGame: 'إنشاء لعبة',
            joinOnlineGame: 'انضم إلى اللعبة',
            gameName: 'اسم اللعبة:',
            gameVisibility: 'رؤية اللعبة:',
            public: 'عام',
            unlisted: 'غير مدرج',
            private: 'خاص',
            gamePassword: 'كلمة مرور اللعبة:',
            gameCode: 'رمز اللعبة:',
            password: 'كلمة السر:',
            leaveGame: 'غادر',
            leaveGameConfirm: 'هل أنت متأكد أنك تريد مغادرة اللعبة؟',
            yes: 'نعم',
            no: 'لا',
            ready: 'جاهز',
            notReady: 'غير جاهز',
            waitingForPlayers: 'في انتظار اللاعبين...',
            copyLink: 'تم نسخ رابط الانضمام إلى الحافظة',
            copyCode: 'تم نسخ رمز اللعبة إلى الحافظة',
            invalidSize: 'حجم اللوحة غير صالح. يرجى اختيار حجم بين 3 و 10',
            invalidGameName: 'تنسيق اسم اللعبة غير صالح. يرجى استخدام الحروف والأرقام والمسافات فقط. يجب أن يكون الطول بين 3 و 20 حرفًا',
            invalidPasswordFormat: 'تنسيق كلمة المرور غير صالح. يرجى استخدام الحروف والأرقام والرموز الخاصة فقط. يجب أن يكون الطول بين 6 و 20 حرفًا',
            invalidGameCode: 'تنسيق رمز اللعبة غير صالح. يرجى استخدام الحروف والأرقام فقط. يجب أن يكون الطول 6 أحرف',
            badRequest: 'حدث خطأ أثناء الانضمام إلى اللعبة. (طلب غير صحيح)',
            unauthorized: 'فشل التوثيق، يرجى المحاولة مرة أخرى',
            forbidden: 'ليس لديك الإذن للانضمام إلى هذه اللعبة',
            notFound: 'تعذر العثور على اللعبة',
            internalServerError: 'حدث خطأ أثناء الانضمام إلى اللعبة',
            notAllowed: 'ليس لديك الإذن لتنفيذ هذا الإجراء',
            gameNotFound: 'لم يتم العثور على اللعبة. يرجى التحقق من الرمز والمحاولة مرة أخرى',
            aiMoveError: 'حدث خطأ أثناء الحصول على حركة AI',
            createGameError: 'حدث خطأ أثناء إنشاء اللعبة عبر الإنترنت',
            joinGameError: 'حدث خطأ أثناء الانضمام إلى اللعبة عبر الإنترنت',
            listGamesError: 'حدث خطأ أثناء الحصول على قائمة الألعاب عبر الإنترنت',
        }
    },
    zh: {
        name: "繁體中文",
        flag: "https://flagsapi.com/CN/flat/32.png",
        translations: {
            title: "井字遊戲",
            selectMode: '选择模式:',
            pvpLocal: 'PvP (本地)',
            pvpOnline: 'PvP (在线)',
            vsBot: '对战机器人',
            boardSize: '选择棋盘大小:',
            botDifficulty: '选择机器人难度:',
            difficultyEasy: '简单',
            difficultyMedium: '中等',
            difficultyImpossible: '不可能',
            difficultyAI: 'AI',
            startingPlayer: '起始玩家:',
            startGame: '开始游戏',
            restartGame: '重新开始',
            nowPlaying: '现在进行:',
            enemyThinking: '敌人在思考...',
            gameTie: '平局!',
            gameWin: '玩家 {player} 获胜!',
            gameWon: '你赢了!',
            helpHeader: '如何玩?',
            online: '在线',
            about: '关于我',
            createOnlineGame: '创建游戏',
            joinOnlineGame: '加入游戏',
            gameName: '游戏名称:',
            gameVisibility: '游戏可见性:',
            public: '公开',
            unlisted: '未列出',
            private: '私人',
            gamePassword: '游戏密码:',
            gameCode: '游戏代码:',
            password: '密码:',
            leaveGame: '离开',
            leaveGameConfirm: '您确定要离开游戏吗?',
            yes: '是',
            no: '否',
            ready: '准备',
            notReady: '未准备好',
            waitingForPlayers: '等待玩家...',
            copyLink: '加入链接已复制到剪贴板',
            copyCode: '游戏代码已复制到剪贴板',
            invalidSize: '无效的棋盘大小。请选择3到10之间的大小。',
            invalidGameName: '无效的游戏名称格式。请仅使用字母、数字和空格。长度必须在3到20个字符之间。',
            invalidPasswordFormat: '无效的密码格式。请仅使用字母、数字和特殊字符。长度必须在6到20个字符之间。',
            invalidGameCode: '无效的游戏代码格式。请仅使用字母和数字。长度必须为6个字符。',
            badRequest: '加入游戏时出错。(错误请求)',
            unauthorized: '身份验证失败，请重试。',
            forbidden: '您无权加入此游戏。',
            notFound: '找不到游戏。',
            internalServerError: '加入游戏时出错。',
            notAllowed: '您无权执行此操作。',
            gameNotFound: '找不到游戏。请检查代码并重试。',
            aiMoveError: '获取AI移动时出错。',
            createGameError: '创建在线游戏时出错。',
            joinGameError: '加入在线游戏时出错。',
            listGamesError: '获取在线游戏列表时出错。',
        }
    },
    ja: {
        name: "日本語",
        flag: "https://flagsapi.com/JP/flat/32.png",
        translations: {
            title: "三目並べ",
            selectMode: 'モードを選択:',
            pvpLocal: 'PvP (ローカル)',
            pvpOnline: 'PvP (オンライン)',
            vsBot: 'ボットに対して',
            boardSize: 'ボードのサイズを選択:',
            botDifficulty: 'ボットの難易度を選択:',
            difficultyEasy: '簡単',
            difficultyMedium: '中級',
            difficultyImpossible: '不可能',
            difficultyAI: 'AI',
            startingPlayer: '開始プレイヤー:',
            startGame: 'ゲーム開始',
            restartGame: 'もう一度プレイ',
            nowPlaying: '現在プレイ中:',
            enemyThinking: '敵は考えている...',
            gameTie: '引き分け!',
            gameWin: 'プレイヤー {player} の勝利!',
            gameWon: 'あなたの勝ち!',
            helpHeader: 'プレーの仕方は?',
            online: 'オンライン',
            about: '私について',
            createOnlineGame: 'ゲームを作成',
            joinOnlineGame: 'ゲームに参加',
            gameName: 'ゲーム名:',
            gameVisibility: 'ゲームの可視性:',
            public: '公開',
            unlisted: '非公開',
            private: 'プライベート',
            gamePassword: 'ゲームのパスワード:',
            gameCode: 'ゲームコード:',
            password: 'パスワード:',
            leaveGame: '去る',
            leaveGameConfirm: 'ゲームを終了してもよろしいですか?',
            yes: 'はい',
            no: 'いいえ',
            ready: '準備完了',
            notReady: '準備ができていない',
            waitingForPlayers: 'プレイヤーを待っています...',
            copyLink: '参加リンクがクリップボードにコピーされました',
            copyCode: 'ゲームコードがクリップボードにコピーされました',
            invalidSize: '無効なボードサイズです。3から10の間のサイズを選択してください。',
            invalidGameName: '無効なゲーム名の形式です。文字、数字、スペースのみを使用してください。長さは3から20文字の間である必要があります。',
            invalidPasswordFormat: '無効なパスワード形式です。文字、数字、特殊文字のみを使用してください。長さは6から20文字の間である必要があります。',
            invalidGameCode: '無効なゲームコード形式です。文字と数字のみを使用してください。長さは6文字である必要があります。',
            badRequest: 'ゲームに参加する際にエラーが発生しました。(不正なリクエスト)',
            unauthorized: '認証に失敗しました。もう一度お試しください。',
            forbidden: 'このゲームに参加する権限がありません。',
            notFound: 'ゲームが見つかりませんでした。',
            internalServerError: 'ゲームに参加する際にエラーが発生しました。',
            notAllowed: 'この操作を実行する権限がありません。',
            gameNotFound: 'ゲームが見つかりませんでした。コードを確認してもう一度お試しください。',
            aiMoveError: 'AIの動きを取得する際にエラーが発生しました。',
            createGameError: 'オンラインゲームの作成中にエラーが発生しました。',
            joinGameError: 'オンラインゲームに参加する際にエラーが発生しました。',
            listGamesError: 'オンラインゲームのリストを取得する際にエラーが発生しました。',
        }
    },
    ko: {
        name: "한국인",
        flag: "https://flagsapi.com/KR/flat/32.png",
        translations: {
            title: "틱택토",
            selectMode: '모드 선택:',
            pvpLocal: 'PvP (로컬)',
            pvpOnline: 'PvP (온라인)',
            vsBot: '봇과의 전투',
            boardSize: '보드 크기 선택:',
            botDifficulty: '봇 난이도 선택:',
            difficultyEasy: '쉬운',
            difficultyMedium: '중간',
            difficultyImpossible: '불가능한',
            difficultyAI: 'AI',
            startingPlayer: '시작 플레이어:',
            startGame: '게임 시작',
            restartGame: '다시 플레이',
            nowPlaying: '현재 플레이 중:',
            enemyThinking: '적이 생각 중...',
            gameTie: '무승부!',
            gameWin: '플레이어 {player} 승리!',
            gameWon: '당신이 이겼습니다!',
            helpHeader: '어떻게 플레이하나요?',
            online: '온라인',
            about: '나에 대해',
            createOnlineGame: '게임 만들기',
            joinOnlineGame: '게임 참가',
            gameName: '게임 이름:',
            gameVisibility: '게임 가시성:',
            public: '공개',
            unlisted: '비공개',
            private: '비공개',
            gamePassword: '게임 비밀번호:',
            gameCode: '게임 코드:',
            password: '암호:',
            leaveGame: '떠나다',
            leaveGameConfirm: '게임을 나가시겠습니까?',
            yes: '예',
            no: '아니',
            ready: '준비 완료',
            notReady: '준비되지 않음',
            waitingForPlayers: '플레이어 대기 중...',
            copyLink: '가입 링크가 클립 보드에 복사되었습니다',
            copyCode: '게임 코드가 클립 보드에 복사되었습니다',
            invalidSize: '잘못된 보드 크기입니다. 3에서 10 사이의 크기를 선택하십시오.',
            invalidGameName: '잘못된 게임 이름 형식입니다. 문자, 숫자, 공백만 사용하십시오. 길이는 3에서 20 자 여야합니다.',
            invalidPasswordFormat: '잘못된 비밀번호 형식입니다. 문자, 숫자, 특수 문자만 사용하십시오. 길이는 6에서 20 자 여야합니다.',
            invalidGameCode: '잘못된 게임 코드 형식입니다. 문자와 숫자만 사용하십시오. 길이는 6 자 여야합니다.',
            badRequest: '게임 참가 중 오류가 발생했습니다. (잘못된 요청)',
            unauthorized: '인증 실패, 다시 시도하십시오.',
            forbidden: '이 게임에 참가할 수있는 권한이 없습니다.',
            notFound: '게임을 찾을 수 없습니다.',
            internalServerError: '게임 참가 중 오류가 발생했습니다.',
            notAllowed: '이 작업을 수행할 수있는 권한이 없습니다.',
            gameNotFound: '게임을 찾을 수 없습니다. 코드를 확인하고 다시 시도하십시오.',
            aiMoveError: 'AI 이동을 가져 오는 중 오류가 발생했습니다.',
            createGameError: '온라인 게임을 만드는 중 오류가 발생했습니다.',
            joinGameError: '온라인 게임에 참가하는 중 오류가 발생했습니다.',
            listGamesError: '온라인 게임 목록을 가져 오는 중 오류가 발생했습니다.',
        }
    }
};